version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbotapp
    container_name: chatbotapp
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: chatbotapp_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: chatbotapp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chatbotapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
